# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AsyncTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5.1.1'
  pod 'RxCocoa', '~> 5.1.1'
  # Pods for AsyncTest

  target 'AsyncTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AsyncTestUITests' do
    # Pods for testing
  end

end
